version: '3'
services:
  lldap:
    container_name: lldap
    image: lldap/lldap:latest
    restart: unless-stopped
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "/home/smurugan/docker/lldap/data:/data"
      # Alternatively, you can mount a volume
      # - "lldap_data:/data"
    environment:
      - UID=1000
      - GID=1000
      - TZ=Asia/Kolkata
      - LLDAP_JWT_SECRET=''
      - LLDAP_KEY_SEED=''
      - LLDAP_LDAP_BASE_DN=dc=homeserver,dc=local
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # You can also set a different database:
      # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
      # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
