
services:
  cadvisor:

    # Check https://github.com/google/cadvisor/releases for latest version tag
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - '8080:8080'

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
    