services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  cadvisor:
    # Check https://github.com/google/cadvisor/releases for latest version tag
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    ports:
      - '8080:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

  grafana:
    image:  grafana/grafana-oss
    ports:
     - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
      

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local