---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Bookmarks:
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/login/
    - DropBox:
        - abbr: DB
          icon: dropbox.png
          href: https://dropbox.com/login/

#- Social:
    #- Reddit:
        #- abbr: RE
          #href: https://reddit.com/

#- Entertainment:
    #- YouTube:
        #- abbr: YT
          #href: https://youtube.com/
