- System:
    - Portainer:
        icon: portainer.png
        href: http://portainer.homeserver.local/
        description: Container Manager
        server: docker-local
        container: portainer
        widget:
          type: portainer
          url: https://portainer.homeserver.local
          env: 2
          key: ""
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: http://nginx.homeserver.local/
        description: Reverse Proxy
        server: docker-local
        container: nginxproxymanager
        widget:
          type: npm
          url: https://nginx.homeserver.local
          username: ''
          password: ''

- Networking:
    - Tailscale:
        icon: tailscale-light.png
        href: https://login.tailscale.com/
        description: VPN / Remote Access
        server: docker-local
        container: tailscale
        widget:
          type: tailscale
          deviceid: ''
          key: ''
    - Pi-hole:
        icon: pi-hole.png
        href: http://pihole.homeserver.local/
        description: Local DNS and DNS Sinkhole
        server: docker-local
        container: pihole
        widget:
          type: pihole
          url: https://pihole.homeserver.local
          key: '' # optional

- Services:
    - Jellyfin:
        icon: jellyfin.png
        href: http://jellyfin.homeserver.local/
        description: Media Server
        server: docker-local
        container: jellyfin
        widget:
          type: jellyfin
          url: https://jellyfin.homeserver.local
          key: ''
          enableBlocks: true
          #enableNowPlaying: true #defaults to true
    - qBittorrent:
        icon: qbittorrent.png
        href: http://qbittorrent.homeserver.local/
        description: Torrents
        server: docker-local
        container: qbittorrent-nox
        widget:
          type: qbittorrent
          url: https://qbittorrent.homeserver.local
          username: ''
          password: ''

- Monitoring:
    - Grafana:
        icon: grafana.png
        href: http://grafana.homeserver.local/
        description: Prometheus Visualizer
        server: docker-local
        container: grafana
        widget:
          type: grafana
          url: https://grafana.homeserver.local
          username: ''
          password: ''
    - Prometheus:
        icon: prometheus.png
        href: http://prometheus.homeserver.local/
        description: System Metrics
        server: docker-local
        container: prometheus
        widget:
          type: prometheus
          url: https://prometheus.homeserver.local

- Backups:
    - rclone:
        icon: rclone.png
        href: https://rclone.homeserver.local/
        description: Encrypted Cloud Backups
        server: docker-local
        container: rclone

- Identity Management:
    - Light LDAP:
        icon: mdi-database
        href: http://lldap.homeserver.local/
        description: Tiny LDAP
        server: docker-local
        container: lldap
    - Authelia:
        icon: authelia.png
        href: http://auth.homeserver.local/
        description: Login and SSO
        server: docker-local
        container: authelia
