---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

- resources:
    cpu: true
    memory: true
    disk:
      - /
      - /mnt/data
    expanded: true
    cputemp: true
    uptime: true
    units: metric
    #refresh: 3000 #optional

- datetime:
    text_size: sm
    format:
      dateStyle: long
      timeStyle: long
      hour12: true

#- greeting:
    #text_size: sm
    #text: homeserver.local
#- search:
    #provider: duckduckgo
    #target: _blank
